#!/usr/bin/env python

# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0

# DeepSpeed Team

from functools import partial
from itertools import chain
import argparse
import glob
import pickle
import itertools
import math
from concurrent.futures import ProcessPoolExecutor, as_completed
import os
import re
import shutil
import socket
import sys
import time
import csv
import json
import torch
import tqdm
#from pprint import pprint

from deepspeed.checkpoint import DeepSpeedCheckpoint
from deepspeed.checkpoint.reshape_utils import get_zero_files
from deepspeed.checkpoint.utils import load_checkpoint_file
from deepspeed.checkpoint import (
    OPTIMIZER_STATE_DICT,
    ZERO_STAGE,
    BASE_OPTIMIZER_STATE,
    SINGLE_PARTITION_OF_FP32_GROUPS,
    PARAM_GROUPS,
    PARAM_SLICE_MAPPINGS,
    MOE_UCP_INFO,
    PARAM_SHAPES,
    PARAM,
    CAT_DIM,
    PARAM_N_SUB_PARAMS,
    SUB_PARAM_SHAPE,
    VOCAB_TENSOR,
    UNIVERSAL_CHECKPOINT_INFO,
    UNIVERSAL_CHECKPOINT_VERSION_KEY,
    UNIVERSAL_CHECKPOINT_VERSION_VALUE,
    VOCABULARY_PARAMETER_PATTERNS,
    PIPELINE_REPLICATED_PARAMETER_PATTERNS,
    TP_REPLICATED_PARAMETER_PATTERNS,
    PARAMETER_TO_AVERAGE_PATTERNS,
    PARAMETER_WITH_ROW_PARALLELISM_PATTERNS,
    PARAMETER_WITH_2_SUB_PARAMS_CAT_DIM_0,
    PARAMETER_WITH_SUB_PARAMS,
    SubparamShape,
)


# ---------------------------------------------------------------------------------------
# Expert parameter names
#
# Expert parameter names are already globally unique by the time anything is written:
# deepspeed.moe.utils.globalize_expert_param_names renumbers them once, in the engine, where
# checkpoint names are minted. This script therefore needs no notion of an expert to address
# them -- it addresses every parameter by name, as it always has.
#
# One thing does not follow from the names alone. param_shapes is recorded by a single rank,
# so it lists only the experts that rank holds -- 8 of 64 for an 8-way expert-parallel model
# -- and the merge stage is driven off that list. The remaining names exist in the model and
# as fragments on disk, but in no rank's param_shapes. Synthesising them is what the two
# functions below are for, and they are the only place here that has to know a name has an
# expert index in it at all.

# Matches routed experts only. Shared experts are replicated on every rank rather than
# distributed, so their names are already unique and must not be rewritten:
#   matches     ...mlp.deepspeed_moe.experts.deepspeed_experts.3.dense_h_to_4h.weight
#   no match    ...mlp.shared_experts.shared_mlp.dense_h_to_4h.weight
EXPERT_PARAM_RE = re.compile(r'^(.*\.deepspeed_experts\.)(\d+)(\..*)$')


def is_expert_param_name(name):
    """True if `name` is a routed-expert parameter, i.e. one that is rank-local."""
    return EXPERT_PARAM_RE.match(name) is not None


def expand_moe_param_shapes(param_group_shapes, moe_info):
    """Materialise every global expert in a `param_shapes` record.

    param_shapes is written by a single rank, so its expert entries name only that rank's
    experts. The merge stage iterates it to decide which parameters to rebuild, so without
    expansion it would rebuild one expert-parallel rank's share and silently ignore the rest.

    Every expert of a layer has the same shape, so the full set is generated by emitting the
    whole global id range for each expert parameter observed. Returns a flat {name: shape}
    dict, matching what the caller built before. Non-MoE checkpoints (moe_info None) are
    flattened unchanged.

    The id already in the name is deliberately discarded rather than used as a base. It is a
    *global* id, and which one it is depends on who wrote the file: _save_moe_checkpoint
    writes an mp_rank file from every rank whose data-parallel rank is 0, i.e. one per
    tensor-parallel rank, and those ranks sit at different expert-parallel ranks. Treating the
    observed id as an offset gives ids outside the valid range for every writer but the first
    (at ep_size=8, num_local=8, a writer holding experts 8..15 emits 8,16,...,64 -- one past
    the last expert, and missing 0..7). Emitting the range is independent of the writer and
    idempotent.
    """
    flat = {}
    for group in param_group_shapes:
        flat.update(group)
    if not moe_info:
        return flat

    ep_size = moe_info.get('ep_size')
    num_local = moe_info.get('num_local_experts')
    if not ep_size or not num_local:
        raise RuntimeError(
            "MoE checkpoint metadata is missing 'ep_size'/'num_local_experts', so the "
            "number of experts cannot be determined. Re-save with a current build.")

    expanded = {}
    for name, shape in flat.items():
        m = EXPERT_PARAM_RE.match(name)
        if m is None:
            expanded[name] = shape
            continue
        prefix, suffix = m.group(1), m.group(3)
        for global_id in range(ep_size * num_local):
            expanded[f'{prefix}{global_id}{suffix}'] = shape
    return expanded


def parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument('--input_folder', type=str, required=True, help='Input DeepSpeed Checkpoint folder')
    parser.add_argument('--output_folder', type=str, required=True, help='Output DeepSpeed checkpoint folder')
    parser.add_argument(
        '--fragment-container',
        action='store_true',
        help='[X-MoE, 2026-09-05] Extract phase writes ONE raw container per ZeRO shard plus an index instead of '
        'one file per (parameter, state, shard); the merge reads fragments by offset. Same atoms, '
        'far fewer files (19k-95k fewer creates and reads for the 10B on Frontier Lustre). Stage 1/2 only.')
    parser.add_argument(
        '--optstate-from-pickle',
        action='store_true',
        help='[X-MoE, 2026-09-06, proposal C9] Build zero/optimizer_state.pt from the shards\' pickles (about 70 KB '
        'each) instead of loading one whole shard per pipeline stage. Falls back to the whole-shard path, with a '
        'printed notice, if a non-sharded value turns out to be a tensor.')
    parser.add_argument('--num_extract_workers',
                        default=4,
                        type=int,
                        help='How many parallel processes to extract zero shards')
    parser.add_argument(
        '--num_merge_workers',
        default=2,
        type=int,
        help=
        'How many parallel processes to merge tp slices (more memory intensive, use much fewer than --num_extract_workers))'
    )
    parser.add_argument('--keep_temp_folder',
                        action='store_true',
                        help='Preserve temporary folder of intermediate checkpoint slice files. Useful for debugging.')
    parser.add_argument('--no_strict',
                        dest='strict',
                        action='store_false',
                        help='Do not perform validity checks on converted checkpoint.')
    parser.add_argument('--inject_missing_state',
                        action='store_true',
                        help='Inject missing checkpoint state into the checkpoint if it is absent.')
    args = parser.parse_args()
    print(f'args = {args}')
    return args


def atoi(text):
    return int(text) if text.isdigit() else text


def natural_keys(text):
    '''
    alist.sort(key=natural_keys) sorts in human order
    http://nedbatchelder.com/blog/200712/human_sorting.html
    (See Toothy's implementation in the comments)
    '''
    return [atoi(c) for c in re.split(r'(\d+)', text)]


def _create_checkpoint_paths(base_folder, iteration, tp_degree, pp_degree):
    path_list = []
    iter_folder = f'iter_{iteration:07d}'
    for i in range(0, tp_degree):
        path_list.append([])
        for j in range(0, pp_degree):
            rank_folder = f'mp_rank_{i:02d}' if pp_degree == 1 else f'mp_rank_{i:02d}_{j:03d}'
            ckpt_path = os.path.join(rank_folder, 'model_optim_rng.pt')
            path_list[i].append(os.path.join(base_folder, iter_folder, ckpt_path))

    return path_list


# ----------------------------------------------------------------------------------------------
# [X-MoE, 2026-09-05] Per-event timing. UCP_TIMING_DIR=<dir> turns it on; unset (or empty) leaves
# every site below at one module-global bool test -- no file, no stat(), no print, same output.
#
# The conversion's cost is spread over 10^4-10^5 small file events in forked worker processes, and
# nothing the converter prints says when any of them happened: the tqdm bars carry no task identity
# and the campaign's awk-stamped log records pipe-arrival times, not event times (ucp_io round 2,
# protocol R1/R8). With the variable set, every process -- the main process and each
# ProcessPoolExecutor worker -- appends one row per event to its OWN file
# <dir>/<role>_<hostname>_<pid>.csv. One file per pid because a forked worker inherits the parent's
# handle: the handle is keyed by os.getpid() and re-opened in the child, and since workers leave
# through os._exit (no atexit, no flush) the file is line-buffered. The pid in the file name joins
# the rows to Darshan's per-process logs. Absolute time is anchored once per file (the '#' line and
# the 'proc' row carry time.time() next to the matching perf_counter_ns); events carry
# perf_counter_ns t0/t1 only.
#
# Columns: event,name,state,tp,dp,path,nbytes,t0_ns,t1_ns,extra. Events: proc, shard_load,
# extract_task, frag_write, container_frag, container_flush, index_write, frag_read, container_read,
# atom_write, merge_task, optstate_write; from the main process the phase rows startup, extract,
# index_build (inside extract), merge, optstate, cleanup, copy_mp, total (absolute times in extra),
# one '*** PHASES {json}' line and <output_folder>/CONVERSION_PHASES.json.
# ----------------------------------------------------------------------------------------------
_TIMING_DIR = os.path.abspath(os.environ['UCP_TIMING_DIR']) if os.environ.get('UCP_TIMING_DIR') else None
_TIMING = _TIMING_DIR is not None
_TIMING_T0_NS = time.perf_counter_ns() if _TIMING else 0    # end of module import (torch, deepspeed)
_TIMING_T0_ABS = time.time() if _TIMING else 0.0
_TIMING_ROLE = 'main'       # set by the main process before each pool is forked; inherited by the workers
_TIMING_FH = None           # (file, csv.writer) opened by THIS pid, or None
_TIMING_PID = None          # pid that opened _TIMING_FH; a forked child sees its parent's pid here
_TIMING_PHASES = {}         # main process: phase -> seconds, for CONVERSION_PHASES.json
_TIMING_FAILED_PID = None   # pid whose timing sink failed: that process records nothing more (see _timing_record)


def _timing_proc_start_abs():
    """Process start as epoch seconds from /proc (10 ms resolution), so the interpreter start and the
    imports that precede _TIMING_T0_ABS are on the same clock. '' if unavailable."""
    try:
        with open('/proc/self/stat') as fh:
            start_ticks = int(fh.read().rsplit(')', 1)[1].split()[19])
        with open('/proc/stat') as fh:
            btime = next(int(line.split()[1]) for line in fh if line.startswith('btime '))
        return btime + start_ticks / os.sysconf('SC_CLK_TCK')
    except Exception:
        return ''


def _timing_writer():
    global _TIMING_FH, _TIMING_PID
    pid = os.getpid()
    if _TIMING_FH is None or _TIMING_PID != pid:
        os.makedirs(_TIMING_DIR, exist_ok=True)
        host = socket.gethostname()
        fh = open(os.path.join(_TIMING_DIR, f'{_TIMING_ROLE}_{host}_{pid}.csv'), 'w', buffering=1, newline='')
        t_abs, t_ns = time.time(), time.perf_counter_ns()
        fh.write(f'# t_abs_start={t_abs!r} t_pc_start_ns={t_ns} host={host} pid={pid} ppid={os.getppid()} '
                 f'role={_TIMING_ROLE}\n')
        writer = csv.writer(fh, lineterminator='\n')
        writer.writerow(['event', 'name', 'state', 'tp', 'dp', 'path', 'nbytes', 't0_ns', 't1_ns', 'extra'])
        writer.writerow([
            'proc', host, '', '', '', '', '', t_ns, t_ns,
            f'pid={pid};ppid={os.getppid()};t_abs={t_abs!r};role={_TIMING_ROLE};'
            f'proc_start_abs={_timing_proc_start_abs()};module_t0_abs={_TIMING_T0_ABS!r};'
            f'module_t0_ns={_TIMING_T0_NS};python={sys.version.split()[0]}'
        ])
        _TIMING_FH, _TIMING_PID = (fh, writer), pid
    return _TIMING_FH[1]


def _timing_record(event, name='', state='', tp='', dp='', path='', nbytes='', t0=0, t1=0, extra=''):
    """Never raises: a failing timing sink (unwritable UCP_TIMING_DIR, ENOSPC/EDQUOT on the CSV) must not fail a
    worker task or the conversion. On the first failure the process prints one line to stderr and records
    nothing more; a forked child, whose pid differs, tries its own file once."""
    global _TIMING_FAILED_PID
    pid = os.getpid()
    if _TIMING_FAILED_PID == pid:
        return
    try:
        _timing_writer().writerow([event, name, state, tp, dp, path, nbytes, t0, t1, extra])
    except Exception as e:
        _TIMING_FAILED_PID = pid
        print(f'*** UCP_TIMING_DIR: timing disabled in pid {pid} ({_TIMING_ROLE}) after {type(e).__name__}: {e}',
              file=sys.stderr)


def _timing_getsize(path):
    """os.path.getsize for a timing row: '' instead of an exception."""
    try:
        return os.path.getsize(path)
    except OSError:
        return ''


def _timing_set_role(role):
    """Main process, before a pool is forked: the workers inherit the role for their file name."""
    global _TIMING_ROLE
    _TIMING_ROLE = role


def _timing_nbytes(x):
    return x.numel() * x.element_size() if torch.is_tensor(x) else 0


def _timing_shard_load(ds_checkpoint, indices_3D, t0, t1, extra=''):
    """shard_load row for one whole-shard torch.load: nbytes from the file size(s), path(s) ';'-joined."""
    pp_index, tp_index, dp_index = indices_3D
    try:
        files = ds_checkpoint.get_zero_files(pp_index=pp_index, tp_index=tp_index, dp_index=dp_index)
        path, nbytes = ';'.join(files), sum(os.path.getsize(f) for f in files)
    except Exception:
        path, nbytes = '', ''
    _timing_record('shard_load', f'pp{pp_index}_tp{tp_index}_dp{dp_index}', '', tp_index, dp_index, path, nbytes, t0,
                   t1, extra)


def _timing_frag_read(path, name, state, tp_index, dp_index):
    """frag_read row around one fragment file's torch.load (file mode); one os.path.getsize per read."""
    t0 = time.perf_counter_ns()
    sd = load_checkpoint_file(path)
    t1 = time.perf_counter_ns()
    _timing_record('frag_read', name, state, tp_index, dp_index, path, _timing_getsize(path), t0, t1)
    return sd


def _timing_container_read(entry, name, state, tp_index, dp_index):
    """container_read row around one _read_fragment (the seek + pread primitive); offset in extra."""
    t0 = time.perf_counter_ns()
    frag = _read_fragment(entry)
    t1 = time.perf_counter_ns()
    _timing_record('container_read', name, state, tp_index, dp_index, entry[0], _timing_nbytes(frag), t0, t1,
                   f'offset={entry[1]}')
    return frag


def _timing_phase_end(event, t0, t_abs0, extra=''):
    """Main process: close the phase that began at (t0, t_abs0) -- one row, seconds into _TIMING_PHASES --
    and return the (perf_counter_ns, time.time()) pair the next phase starts from."""
    t1, t_abs1 = time.perf_counter_ns(), time.time()
    _timing_record(event, t0=t0, t1=t1, extra=f't_abs0={t_abs0!r};t_abs1={t_abs1!r}' + (';' + extra if extra else ''))
    _TIMING_PHASES[event] = (t1 - t0) / 1e9
    return t1, t_abs1


def _timing_phases_report(args):
    """Main process, once, after the universal checkpoint is complete: the 'total' row, one
    '*** PHASES {json}' line and <output_folder>/CONVERSION_PHASES.json. The file sits in the output
    root: post_convert.sh counts the directories under zero/ as atoms and tmp/ is removed."""
    try:
        t1, t_abs1 = time.perf_counter_ns(), time.time()
        _timing_record('total', t0=_TIMING_T0_NS, t1=t1, extra=f't_abs0={_TIMING_T0_ABS!r};t_abs1={t_abs1!r}')
        partition = ['startup', 'extract', 'merge', 'optstate', 'cleanup', 'copy_mp']
        total_s = (t1 - _TIMING_T0_NS) / 1e9
        sum_s = sum(_TIMING_PHASES.get(p, 0.0) for p in partition)
        proc_start = _timing_proc_start_abs()
        report = {f'{p}_s': round(s, 6) for p, s in _TIMING_PHASES.items()}
        report.update({
            'total_s': round(total_s, 6),
            'sum_phases_s': round(sum_s, 6),
            'residual_s': round(total_s - sum_s, 6),
            'phases_partition': partition,
            'index_build_inside_extract': True,
            'import_s': round(_TIMING_T0_ABS - proc_start, 3) if proc_start != '' else None,
            'host': socket.gethostname(),
            'pid': os.getpid(),
            't_start_abs': _TIMING_T0_ABS,
            't_end_abs': t_abs1,
            'proc_start_abs': proc_start if proc_start != '' else None,
            'mode': 'container' if getattr(args, 'fragment_container', False) else 'file',
            'workers_extract': args.num_extract_workers,
            'workers_merge': args.num_merge_workers,
            'input_folder': args.input_folder,
            'output_folder': args.output_folder,
            'timing_dir': _TIMING_DIR,
            'python': sys.version.split()[0],
        })
        print('*** PHASES ' + json.dumps(report))
        with open(os.path.join(args.output_folder, 'CONVERSION_PHASES.json'), 'w') as fh:
            json.dump(report, fh, indent=1)
    except Exception as e:
        print(f'*** UCP_TIMING_DIR: CONVERSION_PHASES.json not written after {type(e).__name__}: {e}', file=sys.stderr)


def _save_checkpoint(file_path, chkpt_sd):
    dir, _ = os.path.split(file_path)
    os.makedirs(dir, exist_ok=True)
    torch.save(chkpt_sd, file_path)


def extract_zero_shards(dir, ds_checkpoint, indices_3D):
    pp_index, tp_index, dp_index = indices_3D
    t_task0 = time.perf_counter_ns() if _TIMING else 0
    sd = ds_checkpoint.get_zero_checkpoint_state(pp_index=pp_index, tp_index=tp_index, dp_index=dp_index)
    if _TIMING:
        _timing_shard_load(ds_checkpoint, indices_3D, t_task0, time.perf_counter_ns())
        cnt0 = cnt

    # pprint(f"Processing {dp_index=} {pp_index=}, {tp_index=}")

    optim_sd = sd[OPTIMIZER_STATE_DICT]
    param_slice_mappings = optim_sd[PARAM_SLICE_MAPPINGS]
    # Experts are replicated across tensor-parallel ranks unless the model was built with
    # expert tensor parallelism; see out_tp below.
    experts_are_replicated = not (ds_checkpoint._get_checkpoint_value(MOE_UCP_INFO) or {}).get(
        'expert_tensor_parallel', False)

    # Expert parameter names are made globally unique by the engine, before ZeRO records them
    # (deepspeed/moe/utils.py globalize_expert_param_names). A checkpoint from a build that
    # instead renamed them here carries a per-rank 'moe_ucp_rank' record and rank-local names;
    # converting it now would write every expert-parallel rank into the same atom directory
    # and report success. There is no way to tell the two apart from the names alone, so key
    # on the record that only the older format has.
    if 'moe_ucp_rank' in optim_sd:
        raise RuntimeError(
            'this checkpoint was written by a build that named expert parameters rank-locally '
            'and renamed them during conversion. That record is no longer produced or read; '
            'expert names are now global in the checkpoint itself. Re-save the checkpoint with '
            'a current build before converting it.')

    universal_checkpoint_info = ds_checkpoint.get_checkpoint_info(UNIVERSAL_CHECKPOINT_INFO)
    pipeline_replicated_params = universal_checkpoint_info.get(PIPELINE_REPLICATED_PARAMETER_PATTERNS, [])
    # print(f'{pipeline_replicated_params=}')

    # dict
    state_groups = optim_sd[BASE_OPTIMIZER_STATE]["state"]
    # list
    fp32_groups = optim_sd[SINGLE_PARTITION_OF_FP32_GROUPS]
    param_groups_cnt = len(state_groups)

    for param_group_id in range(param_groups_cnt):

        flat_state = dict(
            exp_avg=state_groups[param_group_id]["exp_avg"],
            exp_avg_sq=state_groups[param_group_id]["exp_avg_sq"],
            fp32=fp32_groups[param_group_id],
        )

        if "step" in state_groups[param_group_id]:
            flat_state["step"] = state_groups[param_group_id]["step"]

        for name, fragment_mapping in param_slice_mappings[param_group_id].items():
            if pp_index > 0 and any(re.match(pattern, name) for pattern in pipeline_replicated_params):
                # Skip tied weights that are replicated in first and last pp stages
                continue

            # A fragment's directory is keyed by (tp_index, dp_index). For an expert that
            # tensor parallelism does not shard, tp_index says nothing about the tensor, and
            # keying on it splits one expert's fragments across tp_degree directories: the
            # expert-parallel groups are carved from the global rank space with no reference
            # to TP (deepspeed/utils/groups.py), so two ranks holding different fragments of
            # the same expert share an expert-parallel position but need not share a
            # tp_rank. _merge_zero_shards would then find only a subset and the reshape
            # would fail. Collapse them onto tp_index 0; each (expert, dp_index) is still
            # written exactly once, because the expert groups partition the world.
            out_tp = 0 if (experts_are_replicated and is_expert_param_name(name)) else tp_index
            for state_key in flat_state.keys():
                dump_param_fragment(dir, out_tp, dp_index, state_key, flat_state[state_key], name,
                                    fragment_mapping.start, fragment_mapping.numel)
    if _TIMING:
        _timing_record('extract_task', f'pp{pp_index}_tp{tp_index}_dp{dp_index}', '', tp_index, dp_index, dir, '',
                       t_task0, time.perf_counter_ns(), f'mode=file;n_frag={cnt - cnt0}')


def extract_zero_shards_stage3(optim_files, param_shapes, dp_degree, temp_dir, dp_index):
    state_dict = load_checkpoint_file(optim_files[dp_index])

    flat_state = dict(
        exp_avg=state_dict[OPTIMIZER_STATE_DICT]['optimizer_state_dict']['state'][0]["exp_avg"],
        exp_avg_sq=state_dict[OPTIMIZER_STATE_DICT]['optimizer_state_dict']['state'][0]["exp_avg_sq"],
        fp32=state_dict[OPTIMIZER_STATE_DICT]['fp32_flat_groups'][0],
    )

    offset = 0
    for name, shape in param_shapes.items():
        unpartitioned_numel = shape.numel()
        partitioned_numel, _ = _zero_partitioned_param_info(unpartitioned_numel, dp_degree)
        padding_free_numel = min(partitioned_numel, abs(unpartitioned_numel - dp_index * partitioned_numel))
        for state_key in flat_state.keys():
            dump_param_fragment(temp_dir, 0, dp_index, state_key, flat_state[state_key], name, offset,
                                padding_free_numel)
        offset += partitioned_numel


cnt = 0


def dp_index_to_str(dp_index):
    return f"{dp_index:0>2d}"


def dump_param_fragment(dir, tp_index, dp_index, state_name, state_flat_tensor, param_name, offset, numel):

    global cnt  # temp hack

    param_base_path = os.path.join(dir, param_name, str(tp_index))
    os.makedirs(param_base_path, exist_ok=True)

    cnt += 1

    path = os.path.join(param_base_path, f"{state_name}.{dp_index_to_str(dp_index)}")

    #print(f"{param_name}: {offset}: {numel} => {path}")

    # State might be a python int or a tensor
    t0 = time.perf_counter_ns() if _TIMING else 0
    if state_name != "step" and torch.is_tensor(state_flat_tensor):
        state_flat_tensor = state_flat_tensor.narrow(0, offset, numel).clone()
    t1 = time.perf_counter_ns() if _TIMING else 0
    _save_checkpoint(path, state_flat_tensor)
    if _TIMING:
        _timing_record('frag_write', param_name, state_name, tp_index, dp_index, path, _timing_nbytes(state_flat_tensor),
                       t1, time.perf_counter_ns(), f'clone_ns={t1 - t0}')


def _merge_zero_shards(param_base_path, state, tp_degree, slice_shape=None):
    slices = []
    for tp_index in range(tp_degree):
        prefix_path = os.path.join(param_base_path, str(tp_index), f"{state}")
        paths = glob.glob(f"{prefix_path}.*")

        if len(paths) == 0:
            continue

        pattern = re.compile(f"{prefix_path}\\.([0-9]+)")
        dp_indices = set()
        for p in paths:
            m = pattern.match(p)
            if m:
                dp_indices.add(int(m.group(1)))
            else:
                raise ValueError(f"Cannot parse dp_rank from {p}")

        paths = [f"{prefix_path}.{dp_index_to_str(dp_index)}" for dp_index in sorted(list(dp_indices))]
        if _TIMING:
            shards = [
                _timing_frag_read(p, os.path.basename(param_base_path), state, tp_index, dp)
                for dp, p in zip(sorted(dp_indices), paths)
            ]
        else:
            shards = [load_checkpoint_file(p) for p in paths]

        if state == "step":
            assert all(v == shards[0] for v in shards), "All shards must have the same step value"
            slice = shards[0]
        else:
            if slice_shape is None:
                slice = torch.cat(shards, dim=0)
            else:
                slice = torch.cat(shards, dim=0).reshape(slice_shape)

        slices.append(slice)
    return slices


# ----------------------------------------------------------------------------------------------
# [X-MoE, 2026-09-05] Fragment containers (--fragment-container).
#
# Darshan on Frontier showed the conversion of a 10B checkpoint spends its extract phase creating
# ~19k (DP8) to ~95k (DP32) small fragment files -- one per (parameter, state, shard), median
# 10 KB -- and its merge phase reading them back, while the bytes moved take a fraction of that
# time (ucp_io campaign, findings F8/F11/F12). Here each extract worker appends every fragment of
# its shard to ONE raw file (tmp/shard_ppP_tpT_dpD.bin) and records (offset, numel, dtype) per
# (parameter, out_tp, state) in tmp/shard_ppP_tpT_dpD.idx. The merge reads a parameter's DP
# fragments by offset from the containers through cached file handles. The merged atoms are
# produced by the same code path as before, so the universal checkpoint is unchanged.
# ----------------------------------------------------------------------------------------------
_CONTAINER_INDEX = None       # {(name, out_tp, state): {dp: (container_path, offset, numel, dtype_str)} | value}
_CONTAINER_HANDLES = {}       # per process: container_path -> open file


def _container_paths(temp_dir, pp_index, tp_index, dp_index):
    stem = os.path.join(temp_dir, f"shard_pp{pp_index}_tp{tp_index}_dp{dp_index}")
    return stem + '.bin', stem + '.idx'


def extract_zero_shards_container(temp_dir, ds_checkpoint, indices_3D):
    """extract_zero_shards, but every fragment goes into this shard's container file."""
    import numpy as np
    pp_index, tp_index, dp_index = indices_3D
    t_task0 = time.perf_counter_ns() if _TIMING else 0
    sd = ds_checkpoint.get_zero_checkpoint_state(pp_index=pp_index, tp_index=tp_index, dp_index=dp_index)
    if _TIMING:
        _timing_shard_load(ds_checkpoint, indices_3D, t_task0, time.perf_counter_ns())
    optim_sd = sd[OPTIMIZER_STATE_DICT]
    param_slice_mappings = optim_sd[PARAM_SLICE_MAPPINGS]
    experts_are_replicated = not (ds_checkpoint._get_checkpoint_value(MOE_UCP_INFO) or {}).get(
        'expert_tensor_parallel', False)
    if 'moe_ucp_rank' in optim_sd:
        raise RuntimeError('rank-local expert names are no longer supported; re-save the checkpoint with a current build')
    universal_checkpoint_info = ds_checkpoint.get_checkpoint_info(UNIVERSAL_CHECKPOINT_INFO)
    pipeline_replicated_params = universal_checkpoint_info.get(PIPELINE_REPLICATED_PARAMETER_PATTERNS, [])
    state_groups = optim_sd[BASE_OPTIMIZER_STATE]["state"]
    fp32_groups = optim_sd[SINGLE_PARTITION_OF_FP32_GROUPS]
    bin_path, idx_path = _container_paths(temp_dir, pp_index, tp_index, dp_index)
    os.makedirs(temp_dir, exist_ok=True)
    index = {}
    offset_bytes = 0
    t_bin0 = time.perf_counter_ns() if _TIMING else 0
    with open(bin_path, 'wb', buffering=64 << 20) as fh:
        for param_group_id in range(len(state_groups)):
            flat_state = dict(
                exp_avg=state_groups[param_group_id]["exp_avg"],
                exp_avg_sq=state_groups[param_group_id]["exp_avg_sq"],
                fp32=fp32_groups[param_group_id],
            )
            if "step" in state_groups[param_group_id]:
                flat_state["step"] = state_groups[param_group_id]["step"]
            for name, fragment_mapping in param_slice_mappings[param_group_id].items():
                if pp_index > 0 and any(re.match(pattern, name) for pattern in pipeline_replicated_params):
                    continue
                out_tp = 0 if (experts_are_replicated and is_expert_param_name(name)) else tp_index
                for state_key, flat in flat_state.items():
                    if state_key == "step" or not torch.is_tensor(flat):
                        index[(name, out_tp, state_key)] = ('value', flat.item() if torch.is_tensor(flat) else flat)
                        continue
                    t0 = time.perf_counter_ns() if _TIMING else 0
                    frag = flat.narrow(0, fragment_mapping.start, fragment_mapping.numel).contiguous()
                    arr = frag.detach().cpu().numpy()
                    arr.tofile(fh)
                    if _TIMING:
                        _timing_record('container_frag', name, state_key, out_tp, dp_index, bin_path, arr.nbytes, t0,
                                       time.perf_counter_ns(), f'offset={offset_bytes}')
                    index[(name, out_tp, state_key)] = ('frag', offset_bytes, int(frag.numel()), str(arr.dtype))
                    offset_bytes += arr.nbytes
    if _TIMING:
        t_bin1 = time.perf_counter_ns()
        shard = f'pp{pp_index}_tp{tp_index}_dp{dp_index}'
        n_frag = sum(1 for e in index.values() if e[0] == 'frag')
        _timing_record('container_flush', shard, '', tp_index, dp_index, bin_path, offset_bytes, t_bin0, t_bin1,
                       f'n_frag={n_frag}')
        t_idx0 = time.perf_counter_ns()
    with open(idx_path, 'wb') as fh:
        pickle.dump({'bin': bin_path, 'dp': dp_index, 'entries': index}, fh)
    if _TIMING:
        _timing_record('index_write', shard, '', tp_index, dp_index, idx_path, _timing_getsize(idx_path), t_idx0,
                       time.perf_counter_ns(), f'n_entries={len(index)}')
        _timing_record('extract_task', shard, '', tp_index, dp_index, temp_dir, '', t_task0, time.perf_counter_ns(),
                       f'mode=container;n_frag={n_frag}')


def build_container_index(temp_dir):
    """Merge the per-shard indexes into tmp/index.pkl: (name, out_tp, state) -> {dp: entry}. Expert
    fragments are replicated across TP shards (out_tp = 0); the first shard seen wins, identical content."""
    merged = {}
    for idx_path in sorted(glob.glob(os.path.join(temp_dir, 'shard_pp*_tp*_dp*.idx'))):
        with open(idx_path, 'rb') as fh:
            rec = pickle.load(fh)
        for key, entry in rec['entries'].items():
            slot = merged.setdefault(key, {})
            if rec['dp'] not in slot:
                slot[rec['dp']] = (rec['bin'], ) + tuple(entry[1:]) if entry[0] == 'frag' else ('value', entry[1])
    with open(os.path.join(temp_dir, 'index.pkl'), 'wb') as fh:
        pickle.dump(merged, fh)
    n_frag = sum(1 for v in merged.values() for e in v.values() if e[0] != 'value')
    print(f'*** fragment container index: {len(merged)} (parameter, tp, state) keys, {n_frag} fragments, '
          f'{len(glob.glob(os.path.join(temp_dir, "shard_pp*_tp*_dp*.bin")))} container files')
    return merged


def _container_index(slice_dir):
    global _CONTAINER_INDEX
    if _CONTAINER_INDEX is None:
        with open(os.path.join(slice_dir, 'index.pkl'), 'rb') as fh:
            _CONTAINER_INDEX = pickle.load(fh)
    return _CONTAINER_INDEX


def _read_fragment(entry):
    import numpy as np
    path, offset, numel, dtype = entry
    fh = _CONTAINER_HANDLES.get(path)
    if fh is None:
        fh = _CONTAINER_HANDLES[path] = open(path, 'rb', buffering=0)
    fh.seek(offset)
    arr = np.fromfile(fh, dtype=np.dtype(dtype), count=numel)
    if arr.shape[0] != numel:
        raise IOError(f'short read from {path} at {offset}: {arr.shape[0]} of {numel}')
    return torch.from_numpy(arr)


def _merge_zero_shards_container(slice_dir, name, state, tp_degree, slice_shape=None):
    """Container-mode twin of _merge_zero_shards: same return value, fragments read by offset."""
    index = _container_index(slice_dir)
    slices = []
    for tp_index in range(tp_degree):
        slot = index.get((name, tp_index, state))
        if not slot:
            continue
        entries = [slot[dp] for dp in sorted(slot)]
        if state == "step":
            values = [e[1] for e in entries]
            assert all(v == values[0] for v in values), "All shards must have the same step value"
            slice = values[0]
        else:
            if _TIMING:
                shards = [_timing_container_read(e, name, state, tp_index, dp) for dp, e in zip(sorted(slot), entries)]
            else:
                shards = [_read_fragment(e) for e in entries]
            slice = torch.cat(shards, dim=0) if slice_shape is None else torch.cat(shards, dim=0).reshape(slice_shape)
        slices.append(slice)
    return slices


# ----------------------------------------------------------------------------------------------
# [X-MoE, 2026-09-06] Shard metadata without the tensor bytes (proposals C9 and C0 of
# ucp_io/round2/PROPOSALS_0906_2026.md). A ZeRO shard is a torch.save zip: 'data.pkl' (about 70 KB
# at 63B) names every value and, for every tensor, the storage record ('data/<key>'), the storage
# offset, the size and the dtype; the storage records carry the bytes, one record per flat
# partition (45 at 63B, up to 692 MB each). Reading the pickle with the tensors replaced by
# _TensorRef placeholders gives everything the converter needs except the values:
#   C9 (--optstate-from-pickle): zero/optimizer_state.pt holds only non-tensor values, so it can be
#       built from the placeholders' dict; today the same dict is obtained by loading 25.8 GB per
#       pipeline stage (82 s of a 1,344 s 63B conversion for a 2,781-byte file).
#   C0 (--fragments-inplace): the byte offset of a parameter's fragment inside its shard is
#       record_offset + (storage_offset + fragment.start) * itemsize, so the merge can read it
#       from the shard directly. The index has the container mode's format with the shard as the
#       'bin', and the container merge path (_read_fragment, read-only) is reused unchanged.
# Measured before this code was written (round 2, N3/N3c, 2026-09-06): index of a shard about 1 s,
# offsets exact against torch.load, 52 ms per cold 31.5 MB fragment read with four readers.
# ----------------------------------------------------------------------------------------------
class _TensorRef(object):
    """Placeholder for a tensor in a shard's pickle: where its bytes are, not the bytes."""
    __slots__ = ('key', 'dtype', 'storage_offset', 'size', 'numel')

    def __init__(self, key, dtype, storage_offset, size):
        self.key, self.dtype, self.storage_offset, self.size = key, dtype, int(storage_offset), tuple(int(x) for x in size)
        self.numel = int(math.prod(self.size)) if len(self.size) else 1

    def __repr__(self):
        return f'_TensorRef(key={self.key}, dtype={self.dtype}, storage_offset={self.storage_offset}, size={self.size})'


class _Placeholder(object):
    """A storage in the pickle: record key, dtype, element count. Never holds data."""
    __slots__ = ('key', 'dtype', 'numel')

    def __init__(self, key, dtype, numel):
        self.key, self.dtype, self.numel = key, dtype, int(numel)


def _load_shard_meta(path):
    """torch.load without the tensor bytes. Returns (state_dict with _TensorRef placeholders,
    {storage key: byte offset of the record's payload in the file}, pickle size in bytes)."""
    import io
    reader = torch._C.PyTorchFileReader(path)
    names = reader.get_all_records()
    prefix = 'archive/' if ('archive/data.pkl' in names and 'data.pkl' not in names) else ''
    record_offsets = {}
    for n in names:
        if n.startswith(prefix + 'data/'):
            record_offsets[n[len(prefix + 'data/'):]] = int(reader.get_record_offset(n))
    pkl = bytes(reader.get_record(prefix + 'data.pkl'))

    def rebuild_tensor(storage, storage_offset, size, stride, *rest):
        return _TensorRef(storage.key, storage.dtype, storage_offset, size)

    class _MetaUnpickler(pickle.Unpickler):

        def persistent_load(self, pid):
            typename, storage_type, key, location, numel = pid[0], pid[1], pid[2], pid[3], pid[4]
            assert typename == 'storage', f'unknown persistent id {typename!r} in {path}'
            if isinstance(storage_type, str):
                dtype = torch.serialization._get_dtype_from_pickle_storage_type(storage_type)
            else:
                dtype = storage_type.dtype
            return _Placeholder(str(key), dtype, numel)

        def find_class(self, module, name):
            if module == 'torch._utils' and name in ('_rebuild_tensor_v2', '_rebuild_tensor'):
                return rebuild_tensor
            return super().find_class(module, name)

    sd = _MetaUnpickler(io.BytesIO(pkl)).load()
    return sd, record_offsets, len(pkl)


def _walk_for_tensor_refs(obj, found, path='root', depth=0):
    """Collect the paths of every _TensorRef / tensor / _Placeholder inside a value (dicts, lists,
    tuples, objects with __dict__)."""
    if depth > 12:
        return
    if isinstance(obj, (_TensorRef, _Placeholder)) or torch.is_tensor(obj):
        found.append(path)
    elif isinstance(obj, dict):
        for k, v in obj.items():
            _walk_for_tensor_refs(v, found, f'{path}.{k}', depth + 1)
    elif isinstance(obj, (list, tuple)):
        for i, v in enumerate(obj):
            _walk_for_tensor_refs(v, found, f'{path}[{i}]', depth + 1)
    elif hasattr(obj, '__dict__'):
        _walk_for_tensor_refs(vars(obj), found, path, depth + 1)


_NUMPY_DTYPE_OF = {torch.float32: 'float32', torch.float64: 'float64', torch.float16: 'float16',
                   torch.int64: 'int64', torch.int32: 'int32', torch.uint8: 'uint8', torch.int8: 'int8', torch.int16: 'int16'}


def _save_optimizer_state_from_pickle(args, ds_checkpoint):
    """C9: the same output as _save_optimizer_state, built from each stage's shard pickle instead of the
    whole shard. Returns True when zero/optimizer_state.pt was written; False (nothing written) when the
    fast path does not apply, so that the caller runs the whole-shard path."""
    sharded_states = [BASE_OPTIMIZER_STATE, PARAM_SLICE_MAPPINGS, SINGLE_PARTITION_OF_FP32_GROUPS]
    zc = ds_checkpoint.zero_checkpoint

    def stage_optim_sd(pp_index):
        files = zc.get_files_for_rank(pp_index, 0, 0)
        if len(files) != 1:
            return None
        t0 = time.perf_counter_ns() if _TIMING else 0
        sd, _, pkl_bytes = _load_shard_meta(files[0])
        if _TIMING:
            _timing_record('optstate_pickle', f'pp{pp_index}_tp0_dp0', '', 0, 0, files[0], pkl_bytes, t0,
                           time.perf_counter_ns(), 'phase=optstate')
        # what get_state_for_rank does to the non-tensor keys (zero_checkpoint.py): the target dp degree
        # in partition_count and paddings cleared; the sharded states are dropped below, so their padding
        # strip is not needed
        zc._update_partition_count(sd)
        zc._clear_group_paddings(sd)
        return sd[OPTIMIZER_STATE_DICT]

    optim_sd = stage_optim_sd(0)
    if optim_sd is None:
        print('*** --optstate-from-pickle: a reshaped file map (several files per rank); using the whole-shard path')
        return False
    output_sd = {k: v for k, v in optim_sd.items() if k not in sharded_states}
    param_groups = optim_sd[BASE_OPTIMIZER_STATE][PARAM_GROUPS]
    for pp_index in range(1, ds_checkpoint.pp_degree):
        stage_sd = stage_optim_sd(pp_index)
        if stage_sd is None:
            print('*** --optstate-from-pickle: a reshaped file map (several files per rank); using the whole-shard path')
            return False
        stage_groups = stage_sd[BASE_OPTIMIZER_STATE][PARAM_GROUPS]
        if len(stage_groups) > len(param_groups):
            param_groups = stage_groups
    output_sd[PARAM_GROUPS] = param_groups
    refs = []
    _walk_for_tensor_refs(output_sd, refs)
    if refs:
        print(f'*** --optstate-from-pickle: {len(refs)} tensor value(s) among the shared settings ({refs[:3]}); '
              'using the whole-shard path so that they are written with their bytes')
        if _TIMING:
            _timing_record('optstate_pickle_fallback', 'optimizer_state', '', '', '', '', '', 0, 0, ';'.join(refs[:5]))
        return False
    zero_output_folder = os.path.join(args.output_folder, "zero")
    output_file_path = os.path.join(zero_output_folder, f"optimizer_state.pt")
    t0 = time.perf_counter_ns() if _TIMING else 0
    _save_checkpoint(output_file_path, output_sd)
    if _TIMING:
        _timing_record('optstate_write', 'optimizer_state', '', '', '', output_file_path,
                       _timing_getsize(output_file_path), t0, time.perf_counter_ns(), 'source=pickle')
    return True


def _merge_shards(slice_dir, name, state, tp_degree, slice_shape=None):
    if os.path.exists(os.path.join(slice_dir, 'index.pkl')):
        return _merge_zero_shards_container(slice_dir, name, state, tp_degree, slice_shape)
    return _merge_zero_shards(os.path.join(slice_dir, name), state, tp_degree, slice_shape)


def merge_tp_slices(ds_checkpoint, dir, slice_dir, tp_degree, name_and_shape):

    name, shape = name_and_shape
    t_task0 = time.perf_counter_ns() if _TIMING else 0
    slice_base_path = os.path.join(slice_dir, name)
    param_base_path = os.path.join(dir, name)

    universal_checkpoint_info = ds_checkpoint.get_checkpoint_info(UNIVERSAL_CHECKPOINT_INFO)
    replicated_parameters = universal_checkpoint_info.get(TP_REPLICATED_PARAMETER_PATTERNS, [])
    parameters_to_average = universal_checkpoint_info.get(PARAMETER_TO_AVERAGE_PATTERNS, [])
    parameters_with_row_parallelism = universal_checkpoint_info.get(PARAMETER_WITH_ROW_PARALLELISM_PATTERNS, [])
    vocabulary_parameters = universal_checkpoint_info.get(VOCABULARY_PARAMETER_PATTERNS, [])
    parameters_with_2_sub_params_cat_dim_0 = universal_checkpoint_info.get(PARAMETER_WITH_2_SUB_PARAMS_CAT_DIM_0, [])
    parameter_with_sub_params = universal_checkpoint_info.get(PARAMETER_WITH_SUB_PARAMS, [])

    unmatched_patterns = set(replicated_parameters + parameters_to_average + parameters_with_row_parallelism +
                             vocabulary_parameters + parameters_with_2_sub_params_cat_dim_0)
    unmatched_patterns.update(chain.from_iterable(SubparamShape(**s).patterns for s in parameter_with_sub_params))

    def get_matched_pattern(patterns_, name_):
        matched_ = [pattern_ for pattern_ in patterns_ if re.match(pattern_, name_)]
        assert len(matched_) <= 1, f'Got more than one matching patterns={matched_} for {name_}'
        if matched_:
            pattern_ = matched_[0]
            unmatched_patterns.discard(pattern_)
            return pattern_
        return None

    def get_matched_sub_params_pattern(name_):
        for subparam_shape_dict in parameter_with_sub_params:
            subparam_shape = SubparamShape(**subparam_shape_dict)
            for pattern_ in subparam_shape.patterns:
                if re.match(pattern_, name_):
                    unmatched_patterns.discard(pattern_)
                    return subparam_shape
        return None

    matched_sub_params_shape = get_matched_sub_params_pattern(name)

    step_merged = _merge_shards(slice_dir, name, "step", tp_degree, shape)
    if step_merged:
        t0 = time.perf_counter_ns() if _TIMING else 0
        _save_checkpoint(os.path.join(param_base_path, f"step.pt"), step_merged[0])
        if _TIMING:
            _timing_record('atom_write', name, 'step', '', '', os.path.join(param_base_path, "step.pt"),
                           _timing_nbytes(step_merged[0]), t0, time.perf_counter_ns())

    for state in ("fp32", "exp_avg", "exp_avg_sq"):
        t_read0 = time.perf_counter_ns() if _TIMING else 0
        slices = _merge_shards(slice_dir, name, state, tp_degree, shape)
        t_read1 = time.perf_counter_ns() if _TIMING else 0
        final_path = os.path.join(param_base_path, f"{state}.pt")

        #print(f"Expected shape: {shape}")
        #print(f"Fragment sizes:", list(frag.shape for frag in slices))
        ckpt_dict = {}
        if get_matched_pattern(replicated_parameters, name):
            if len(slices) > 1:
                assert all([slices[0].equal(other_slice) for other_slice in slices[1:]])
            param = slices[0]
            # print(f'replicate {name} using first slice')
        elif get_matched_pattern(parameters_to_average, name):
            param = sum(slices) / len(slices)
            # print(f'merge {name} using average')
        elif get_matched_pattern(parameters_with_2_sub_params_cat_dim_0, name):
            cat_dim = 0
            chunked_slices = [torch.chunk(s, 2, dim=cat_dim) for s in slices]
            merged_chunks_0 = torch.cat([s[0] for s in chunked_slices], dim=cat_dim)
            merged_chunks_1 = torch.cat([s[1] for s in chunked_slices], dim=cat_dim)
            param = torch.cat([merged_chunks_0, merged_chunks_1], dim=cat_dim)
            ckpt_dict[CAT_DIM] = cat_dim
            ckpt_dict[PARAM_N_SUB_PARAMS] = 2
        elif matched_sub_params_shape:
            merged_chunks = []
            partition_dim = matched_sub_params_shape.partition_dim

            sub_dim_sizes = matched_sub_params_shape.shape[partition_dim]
            if not isinstance(sub_dim_sizes, tuple):
                sub_dim_sizes = (sub_dim_sizes, )

            partition_shape = [sum(d) if isinstance(d, tuple) else d for d in matched_sub_params_shape.shape]
            partition_shape = [d // tp_degree if i == partition_dim else d for i, d in enumerate(partition_shape)]
            slices = [s.view(partition_shape) for s in slices]

            offset = 0
            for sub_dim_size in sub_dim_sizes:
                part_sub_dim_size = sub_dim_size // tp_degree
                merged_chunks.append(
                    torch.cat([s.narrow(partition_dim, offset, part_sub_dim_size) for s in slices], dim=partition_dim))
                offset += part_sub_dim_size
            param = torch.cat(merged_chunks, dim=partition_dim)
            ckpt_dict[SUB_PARAM_SHAPE] = matched_sub_params_shape
        else:
            cat_dim = 1 if get_matched_pattern(parameters_with_row_parallelism, name) else 0
            # print(f"merge {name} with CAT DIM: {cat_dim}")
            param = torch.cat(slices, dim=cat_dim)
            ckpt_dict[CAT_DIM] = cat_dim

        if get_matched_pattern(vocabulary_parameters, name):
            #print(f"Before {param.shape=}")
            # strip padding
            original_vocab_size = universal_checkpoint_info['original_vocab_size']
            param = param[:original_vocab_size, :]
            ckpt_dict[VOCAB_TENSOR] = True
            #print(f"After {param.shape=}")

        #print(f"Final shape: {param.shape}")
        ckpt_dict[PARAM] = param
        _save_checkpoint(final_path, ckpt_dict)
        if _TIMING:
            _timing_record('atom_write', name, state, '', '', final_path, _timing_nbytes(param), t0,
                           time.perf_counter_ns(),
                           f'n_slices={len(slices)};read_ns={t_read1 - t_read0};merge_ns={t0 - t_read1}')

    if _TIMING:
        _timing_record('merge_task', name, '', tp_degree, '', param_base_path, '', t_task0, time.perf_counter_ns(),
                       f'n_slices={len(slices)}')
    return unmatched_patterns


def merge_zero3_slices(dp_degree, dir, slice_dir, name):
    slice_base_path = os.path.join(slice_dir, name)
    param_base_path = os.path.join(dir, name)

    for state in ("fp32", "exp_avg", "exp_avg_sq"):
        slices = _merge_zero_shards(slice_base_path, state, 1)
        final_path = os.path.join(param_base_path, f"{state}.pt")
        _save_checkpoint(final_path, slices[0])


def _do_parallel_work(do_work, work_chunks, num_workers):
    results = []
    if num_workers > 1:
        with ProcessPoolExecutor(max_workers=num_workers) as executor:
            future_list = [executor.submit(do_work, work) for work in work_chunks]
            # as_completed, not submission order: iterating the list in order leaves the progress
            # bar pinned at 0% until the FIRST task finishes, which on a multi-minute extract is
            # indistinguishable from a hang -- and a killed conversion leaves a stale tmp/ behind.
            # Safe because the one caller that uses the return value intersects the results as
            # sets, so ordering carries no information.
            for f in tqdm.tqdm(as_completed(future_list), total=len(future_list)):
                results.append(f.result())
    else:
        # No parallel pass for unit testing
        # We can't create child processes in tests
        for work in tqdm.tqdm(work_chunks):
            results.append(do_work(work))
    return results


def _extract_zero_shard_files(args, ds_checkpoint, temp_dir):
    _3d_range_list = list(
        itertools.product(range(ds_checkpoint.pp_degree), range(ds_checkpoint.tp_degree),
                          range(ds_checkpoint.dp_degree)))
    #pprint(f'{_3d_range_list=}')

    # One task == one ZeRO shard, held whole in memory by its worker. Workers beyond the task
    # count do nothing but still cost a process, and each concurrent worker costs one shard of RAM
    # -- tens of GiB for a large MoE model. Clamp, and say so.
    num_workers = min(args.num_extract_workers, len(_3d_range_list))
    if num_workers != args.num_extract_workers:
        print(f'*** Clamping --num_extract_workers {args.num_extract_workers} -> {num_workers} '
              f'(only {len(_3d_range_list)} ZeRO shards to extract)')

    shard_gib = os.path.getsize(ds_checkpoint.zero_checkpoint.file_list[0]) / 2**30
    print(f'*** Extracting {len(_3d_range_list)} ZeRO shards of {shard_gib:.1f} GiB with '
          f'{num_workers} worker(s): expect up to ~{num_workers * shard_gib:.0f} GiB resident')

    if _TIMING:
        _timing_set_role('extract')
    if getattr(args, 'fragment_container', False):
        print('*** fragment containers: one raw file + index per ZeRO shard instead of per-fragment files')
        do_work = partial(extract_zero_shards_container, temp_dir, ds_checkpoint)
        _do_parallel_work(do_work, _3d_range_list, num_workers)
        t0, t_abs0 = (time.perf_counter_ns(), time.time()) if _TIMING else (0, 0.0)
        build_container_index(temp_dir)
        if _TIMING:
            _timing_phase_end('index_build', t0, t_abs0, f'path={os.path.join(temp_dir, "index.pkl")}')
        return
    do_work = partial(extract_zero_shards, temp_dir, ds_checkpoint)
    _do_parallel_work(do_work, _3d_range_list, num_workers)


def _extract_zero_shard_files_stage3(args, optim_files, param_shapes, dp_degree, temp_dir):
    if _TIMING:
        _timing_set_role('extract')
    do_work = partial(extract_zero_shards_stage3, optim_files, param_shapes, dp_degree, temp_dir)
    _do_parallel_work(do_work, list(range(dp_degree)), args.num_extract_workers)


def _merge_tp_slice_files(args, ds_checkpoint, slice_shapes, temp_dir):
    if _TIMING:
        _timing_set_role('merge')
    zero_output_folder = os.path.join(args.output_folder, "zero")
    do_work = partial(merge_tp_slices, ds_checkpoint, zero_output_folder, temp_dir, ds_checkpoint.tp_degree)
    unmatched_patterns_lists = _do_parallel_work(do_work, list(slice_shapes.items()), args.num_merge_workers)

    # verify that all patterns were used
    # if a pattern was not used by any of the workers, then it was not used at all -> assert/alert
    sets = [set(lst) for lst in unmatched_patterns_lists]
    unmatched_patterns = list(set.intersection(*sets))
    if args.strict:
        assert not unmatched_patterns, f'Unused patterns={unmatched_patterns} while merging tp slices'
    elif unmatched_patterns:
        print(f'Warning: Unused patterns={unmatched_patterns} while merging tp slices')


def _merge_zero3_slice_files(args, param_shapes, dp_degree, temp_dir):
    if _TIMING:
        _timing_set_role('merge')
    zero_output_folder = os.path.join(args.output_folder, "zero")
    do_work = partial(merge_zero3_slices, dp_degree, zero_output_folder, temp_dir)
    _do_parallel_work(do_work, param_shapes.keys(), args.num_merge_workers)


def _zero_partitioned_param_info(unpartitioned_numel, world_size):
    remainder = unpartitioned_numel % world_size
    padding_numel = (world_size - remainder) if remainder else 0
    partitioned_numel = math.ceil(unpartitioned_numel / world_size)
    return partitioned_numel, padding_numel


def _parse_model_states_stage3(files):
    return load_checkpoint_file(files[0])[PARAM_SHAPES]


def _save_optimizer_state(args, ds_checkpoint):
    if getattr(args, 'optstate_from_pickle', False) and _save_optimizer_state_from_pickle(args, ds_checkpoint):
        return
    sharded_states = [BASE_OPTIMIZER_STATE, PARAM_SLICE_MAPPINGS, SINGLE_PARTITION_OF_FP32_GROUPS]
    t0 = time.perf_counter_ns() if _TIMING else 0
    sd = ds_checkpoint.get_zero_checkpoint_state(pp_index=0, tp_index=0, dp_index=0)
    if _TIMING:
        _timing_shard_load(ds_checkpoint, (0, 0, 0), t0, time.perf_counter_ns(), 'phase=optstate')

    optim_sd = sd[OPTIMIZER_STATE_DICT]
    output_sd = {k: v for k, v in optim_sd.items() if k not in sharded_states}
    param_groups = optim_sd[BASE_OPTIMIZER_STATE][PARAM_GROUPS]
    # Under pipeline parallelism the group list is per-stage (MoE groups exist only on
    # stages that hold MoE layers -- with --first-k-dense-replace, stage 0 may hold
    # none). Same treatment as the MOE_UCP_INFO accessor: scan the stages and record
    # the richest list, so the saved metadata describes the MoE-bearing stages rather
    # than whichever stage happened to be index 0. The load side pairs groups
    # positionally per rank and falls back safely on a count mismatch, so this only
    # improves the recorded metadata; per-parameter state is name-addressed and
    # unaffected either way.
    for pp_index in range(1, ds_checkpoint.pp_degree):
        t0 = time.perf_counter_ns() if _TIMING else 0
        stage_sd = ds_checkpoint.get_zero_checkpoint_state(pp_index=pp_index, tp_index=0, dp_index=0)
        if _TIMING:
            _timing_shard_load(ds_checkpoint, (pp_index, 0, 0), t0, time.perf_counter_ns(), 'phase=optstate')
        stage_groups = stage_sd[OPTIMIZER_STATE_DICT][BASE_OPTIMIZER_STATE][PARAM_GROUPS]
        if len(stage_groups) > len(param_groups):
            param_groups = stage_groups
    output_sd[PARAM_GROUPS] = param_groups
    zero_output_folder = os.path.join(args.output_folder, "zero")
    output_file_path = os.path.join(zero_output_folder, f"optimizer_state.pt")
    t0 = time.perf_counter_ns() if _TIMING else 0
    _save_checkpoint(output_file_path, output_sd)
    if _TIMING:
        _timing_record('optstate_write', 'optimizer_state', '', '', '', output_file_path,
                       _timing_getsize(output_file_path), t0, time.perf_counter_ns())


def _save_optimizer_state_stage3(args, optim_files):
    sd = load_checkpoint_file(optim_files[0])
    output_sd = sd[OPTIMIZER_STATE_DICT]
    output_sd[PARAM_GROUPS] = output_sd[OPTIMIZER_STATE_DICT][PARAM_GROUPS]
    zero_output_folder = os.path.join(args.output_folder, "zero")
    output_file_path = os.path.join(zero_output_folder, f"optimizer_state.pt")
    _save_checkpoint(output_file_path, output_sd)


def _get_optim_files(checkpoint_dir):
    # The MoE save path also writes expp_rank_<n>_mp_rank_<m>_optim_states.pt placeholders
    # ({'optimizer': None}), which match "*_optim_states.pt" but are not ZeRO shards. Sorted
    # naturally, 'expp_rank_0...' precedes 'fp16_zero_pp_rank_0...', so _get_zero_stage would
    # read one of the placeholders and raise KeyError: 'optimizer_state_dict'. reshape_utils
    # already knows the three real ZeRO prefixes; ask it.
    files = get_zero_files(checkpoint_dir)
    if not files:
        # Most common cause by far: a weights-only folder. Say so, rather than making the user
        # guess which of the three prefixes was expected.
        raise FileNotFoundError(
            f"no ZeRO optimizer files (zero_pp_rank_* / bf16_zero_pp_rank_* / fp16_zero_pp_rank_*) "
            f"in '{checkpoint_dir}'. Universal checkpointing converts optimizer state, so a "
            f"weights-only checkpoint (e.g. one produced by an HF import tool) is not a valid input.")
    return files


def _get_model_state_files(checkpoint_dir):
    return _get_checkpoint_files(checkpoint_dir, "*_model_states.pt")


def _get_checkpoint_files(checkpoint_dir, glob_pattern):
    ckpt_files = sorted(glob.glob(os.path.join(checkpoint_dir, glob_pattern)), key=natural_keys)

    if len(ckpt_files) == 0:
        raise FileNotFoundError(f"can't find {glob_pattern} files in directory '{checkpoint_dir}'")

    return ckpt_files


def _get_zero_stage(optim_files):
    state_dict = load_checkpoint_file(optim_files[0])
    optimizer_state = state_dict[OPTIMIZER_STATE_DICT]
    zero_stage = optimizer_state.get(ZERO_STAGE, 1)
    return zero_stage


def _inject_missing_state(ds_checkpoint):
    if UNIVERSAL_CHECKPOINT_INFO not in ds_checkpoint.global_state:
        sd = load_checkpoint_file(ds_checkpoint.mp_rank_files[0])
        if UNIVERSAL_CHECKPOINT_INFO not in sd:
            ds_checkpoint.global_state[UNIVERSAL_CHECKPOINT_INFO] = {}
            ds_checkpoint.global_state[UNIVERSAL_CHECKPOINT_INFO][
                UNIVERSAL_CHECKPOINT_VERSION_KEY] = UNIVERSAL_CHECKPOINT_VERSION_VALUE


def _check_for_required_state(ds_checkpoint):
    universal_checkpoint_info = ds_checkpoint.get_checkpoint_info(UNIVERSAL_CHECKPOINT_INFO)
    assert universal_checkpoint_info is not None, f'Required {UNIVERSAL_CHECKPOINT_INFO} state is missing in checkpoint. Verify that client creates this state.'


def main(args):
    print(f'Convert DeepSpeed Checkpoint to Universal Checkpoint')

    print(f'Converting DeepSpeed checkpoint in {args.input_folder} to Universal checkpoint in {args.output_folder}')

    optim_files = _get_optim_files(args.input_folder)
    zero_stage = _get_zero_stage(optim_files)

    if zero_stage <= 2:
        ds_checkpoint = DeepSpeedCheckpoint(args.input_folder)
        if args.inject_missing_state:
            _inject_missing_state(ds_checkpoint)
        else:
            _check_for_required_state(ds_checkpoint)

        iteration = ds_checkpoint.get_iteration()
        #_create_latest_file(args.output_folder, iteration)
        checkpoint_paths = _create_checkpoint_paths(args.output_folder, iteration, ds_checkpoint.tp_degree,
                                                    ds_checkpoint.pp_degree)

        slice_shapes = []
        for mp_rank_file in ds_checkpoint.mp_rank_files:
            mp_sd = load_checkpoint_file(mp_rank_file)
            if PARAM_SHAPES not in mp_sd or mp_sd[PARAM_SHAPES] is None:
                raise KeyError(
                    f"'{PARAM_SHAPES}' is missing from {os.path.basename(mp_rank_file)}. It records "
                    f"which parameters the optimizer's flat buffers hold, and cannot be "
                    f"reconstructed after the fact. Re-save the checkpoint with a build that "
                    f"records it.")
            slice_shapes += mp_sd[PARAM_SHAPES]

        # Flatten, merging duplicates for tp>1. For MoE this also materialises every global
        # expert: param_shapes is written by one rank and names only its local experts, so
        # without this the merge phase would skip all but one expert-parallel rank's share.
        # If experts are present but their metadata is not, the number of experts cannot be
        # known and expand_moe_param_shapes would silently emit one expert-parallel rank's
        # share. That converts without error and dies on the first missing atom at resume, so
        # refuse here where the cause is still visible.
        moe_info = ds_checkpoint._get_checkpoint_value(MOE_UCP_INFO)
        flat_names = {name for group in slice_shapes for name in group}
        if moe_info is None and any(is_expert_param_name(name) for name in flat_names):
            raise RuntimeError(
                f"this checkpoint has expert-parallel parameters but no '{MOE_UCP_INFO}' "
                f"record in any of its {len(ds_checkpoint.mp_rank_files)} model-state files, "
                f"so the total number of experts cannot be determined. It was written by a "
                f"build that predates the record; re-save it with a current build.")

        # An expert implementation that stacks all of a rank's experts into one tensor leaves
        # those parameters with expert-parallel-rank-local names. Every rank then writes the
        # same name, so the atoms silently overwrite each other and the converted checkpoint
        # holds one rank's experts presented as all of them. The engine cannot refuse at save
        # time without killing training that never intended to convert, so it records the fact
        # and the refusal lands here, where the user is asking for the conversion.
        if moe_info is not None and not moe_info.get('expert_names_globalized', True):
            raise RuntimeError(
                "this checkpoint's expert parameters have expert-parallel-rank-local names, so "
                "each expert-parallel rank's optimizer state would be written to the same "
                "place and all but one rank's experts would be lost. The expert module used "
                "stacks its local experts into shared tensors, which have no per-expert name "
                "to make globally unique. Universal checkpointing does not support that expert "
                "implementation; re-train with the unfused Experts module to convert.")

        slice_shapes = expand_moe_param_shapes(slice_shapes, moe_info)
        if moe_info:
            n_expert = sum(1 for k in slice_shapes if is_expert_param_name(k))
            print(f'*** MoE checkpoint: {n_expert} expert parameters across '
                  f"{moe_info.get('ep_size')} expert-parallel ranks")
        temp_dir = os.path.join(args.output_folder, 'tmp')

        if _TIMING:
            t_ph, t_ph_abs = _timing_phase_end('startup', _TIMING_T0_NS, _TIMING_T0_ABS)
        print('*** 1. Extracting ZeRO fragments')
        _extract_zero_shard_files(args, ds_checkpoint, temp_dir)
        if _TIMING:
            t_ph, t_ph_abs = _timing_phase_end('extract', t_ph, t_ph_abs)

        print('*** 2. Merging slices .....')
        _merge_tp_slice_files(args, ds_checkpoint, slice_shapes, temp_dir)
        if _TIMING:
            t_ph, t_ph_abs = _timing_phase_end('merge', t_ph, t_ph_abs)

        print('*** 3. Saving common optimizer states')
        _save_optimizer_state(args, ds_checkpoint)
        if _TIMING:
            t_ph, t_ph_abs = _timing_phase_end('optstate', t_ph, t_ph_abs)

        if not args.keep_temp_folder:
            shutil.rmtree(temp_dir, ignore_errors=True)
        if _TIMING:
            t_ph, t_ph_abs = _timing_phase_end('cleanup', t_ph, t_ph_abs)

        # Copy mp* files into output folder
        for f in glob.glob(os.path.join(args.input_folder, 'mp*')):
            shutil.copy2(f, args.output_folder)
        if _TIMING:
            _timing_phase_end('copy_mp', t_ph, t_ph_abs)

    else:
        model_files = _get_model_state_files(args.input_folder)
        param_shapes = _parse_model_states_stage3(model_files)
        param_shapes = {k: v for d in param_shapes for k, v in d.items()}
        dp_degree = len(model_files)

        temp_dir = os.path.join(args.output_folder, 'tmp')

        if _TIMING:
            t_ph, t_ph_abs = _timing_phase_end('startup', _TIMING_T0_NS, _TIMING_T0_ABS)
        print('*** 1. Extracting ZeRO fragments')
        _extract_zero_shard_files_stage3(args, optim_files, param_shapes, dp_degree, temp_dir)
        if _TIMING:
            t_ph, t_ph_abs = _timing_phase_end('extract', t_ph, t_ph_abs)

        print('*** 2. Merging slices .....')
        _merge_zero3_slice_files(args, param_shapes, dp_degree, temp_dir)
        if _TIMING:
            t_ph, t_ph_abs = _timing_phase_end('merge', t_ph, t_ph_abs)

        print('*** 3. Saving common optimizer states')
        _save_optimizer_state_stage3(args, optim_files)
        if _TIMING:
            t_ph, t_ph_abs = _timing_phase_end('optstate', t_ph, t_ph_abs)

        if not args.keep_temp_folder:
            shutil.rmtree(temp_dir, ignore_errors=True)
        if _TIMING:
            t_ph, t_ph_abs = _timing_phase_end('cleanup', t_ph, t_ph_abs)

        # Copy *model_states files into output folder
        for f in glob.glob(os.path.join(args.input_folder, '*model_states.pt')):
            shutil.copy2(f, args.output_folder)
        if _TIMING:
            _timing_phase_end('copy_mp', t_ph, t_ph_abs)

    # Update latest to output folder
    checkpoint_root_folder, step_folder = os.path.split(args.output_folder)
    latest_file = os.path.join(checkpoint_root_folder, 'latest_universal')
    with open(latest_file, "w") as f:
        f.write(step_folder)

    if _TIMING:
        _timing_phases_report(args)
    print('*** Done!')


if __name__ == "__main__":
    args = parse_arguments()
    main(args)
